### ISSUE TITLE
Data Rebalancing

### ISSUE THREAD

**Issue by ashwanthkumar** [ashwanthkumar/suuchi#49]
Add ability for the cluster to 
- scale out - addition of new nodes 
- scale down - nodes going down.
- Anti Entropy - Refer #50 for more details
## Tasks
- [ ] It's relatively easy to do data rebalancing with ConsistentHashRing, but given the generic nature of the RoutingStrategy. We need to decide on the interactions of `Rebalancer` with that of `RoutingStrategy`
- [ ] Implement / integrate membership with the `Server`. Once we've Membership, think about how would it integrate with Partitioner / RoutingStrategy for maintaining the list of nodes.
## Dependencies
- [ ] While re-balancing we need to know what keys to migrate which needs an Anti-entropy implementation #50
